name: Access Request
description: For requesting access to additional resources. Such as Repos, Teams, Hardware, Environments.
title: "[Access Request]: "
labels: ["Access Scope", "Access Request", "Priority 3"]
projects: ["Hypertrophik/Access Requests",]
assignees:
  - 
  
body:
  - type: markdown
    attributes:
      value: |
        ## Access Request Details
        
  - type: input
    id: requester_name
    attributes:
      label: Requester Name
      description: Your full name
      placeholder: 'e.g. John Doe'
    validations:
      required: true
      
  - type: input
    id: requester_email
    attributes:
      label: Requester Email
      description: Your email address
      placeholder: 'e.g. john.doe@suse.com'
    validations:
      required: true
      
  - type: input
    id: team
    attributes:
      label: Team
      description: Your team
      placeholder: 'e.g. DevOps Team'
    validations:
      required: true
      
  - type: textarea
    id: resource_name
    attributes:
      label: Name of Resource
      description: Type of resource for which access is requested
    validations:
      required: true
      
  - type: input
    id: access_level
    attributes:
      label: Access Level Needed
      description: Level of access required
    validations:
      required: true

  - type: textarea
    id: access_purpose
    attributes:
      label: Purpose of Access
      description: Brief explanation of why access is needed
      placeholder: 'e.g. To contribute to Repository XYZ'
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Any other relevant information or special instructions
      placeholder: 'e.g. Access needed for a specific timeframe for auditing purposes'

  - type: markdown
    attributes:
      value: |
        ## Approval

  - type: input
    id: manager_approval
    attributes:
      label: Manager/Supervisor Approval
      description: github username
      placeholder: '@hamburgler'
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure all necessary steps are completed
      options:
        - label: Verified requestor information
        - label: Verified resource details
        - label: Received necessary approvals
        - label: Updated access control records
          
